dia=param("body_diameter",240.0)
depth=param("body_depth",28.0)
wall=param("body_wall",2.7)
back=param("body_back_thickness",3.0)
opening=param("body_service_opening",64.0)
seat_z=param("body_seat_height",21.8)
seat_thick=param("body_seat_thickness",2.8)
seat_width=param("body_seat_width",5.3)
neck_w=param("body_neck_width",28.0)
neck_h=param("body_neck_height",10.0)
neck_reach=param("body_neck_reach",38.0)
neck_y=param("body_neck_vertical",-50.0)
tenon=param("body_tenon_width",20.0)
tenon_l=param("body_tenon_length",25.0)
tenon_offset=param("body_tenon_rear_offset",18.0)
body=Cylinder(dia/2,depth,align=(Align.CENTER,Align.CENTER,Align.MIN))
body=body-Pos(0,0,back)*Cylinder(dia/2-wall,depth,align=(Align.CENTER,Align.CENTER,Align.MIN))
body=body-Box(opening,opening,2*depth)
ledge=Pos(0,0,seat_z-seat_thick)*extrude(Circle(dia/2-wall)-Circle(dia/2-wall-seat_width),amount=seat_thick)
body=body+ledge
neck=Pos(0,neck_y,-neck_reach)*Box(neck_w,neck_h,neck_reach+back,align=(Align.CENTER,Align.MIN,Align.MIN))
pin=Pos(0,neck_y-tenon_l,-tenon_offset)*Box(tenon,tenon_l+neck_h/2,tenon,align=(Align.CENTER,Align.MIN,Align.CENTER))
body=body+neck+pin
body.color=Color(0.94,0.53,0.025)
assert len(body.solids())==1
publish("body",body,"Clock body",material="petg")